sensor:
  - platform: command_line
    name: kitchen_fan
    command: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.1.37 /home/pi/bluetooth/get_kitchen_fan.sh"

fan:
  - platform: template
    fans:
      kitchen_fan:
        unique_id: kitchen_fan
        friendly_name: "Fläkten"
        percentage_template: "{{ (states('sensor.kitchen_fan')|float * 12.5)|int }}"
        value_template: >
          {% if states('sensor.kitchen_fan')|int > 0 -%}
            on
          {%- else -%}
            off
          {%- endif %}
        turn_on:
          - service: shell_command.set_kitchen_fan
            data_template:
              value: 5
          - delay: 2
          - service: homeassistant.update_entity
            entity_id: sensor.kitchen_fan
        turn_off:
          - service: shell_command.set_kitchen_fan
            data_template:
              value: 0
          - delay: 2
          - service: homeassistant.update_entity
            entity_id: sensor.kitchen_fan
        set_percentage:
          - service: shell_command.set_kitchen_fan
            data_template:
              value: "{{ (percentage|float / 12.5)|int }}"
          - delay: 2
          - service: homeassistant.update_entity
            entity_id: sensor.kitchen_fan

shell_command:
  set_kitchen_fan: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa pi@192.168.1.37 /home/pi/bluetooth/set_kitchen_fan.sh {{ value }}
